<?php

namespace AppBundle\Repository;

/**
 * MemberLoanRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MemberLoanRepository extends \Doctrine\ORM\EntityRepository
{
}
