# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]

  app.form.registration:
    class: AppBundle\Form\RegistrationType
    tags:
      - {name: form.type, alias: app_user_registration}

#  app.form.profile:
#  	class: AppBundle\Form\ProfileType
#  	arguments: ["@security.token_storage"]
#  	tags:
#      - {name: form.type, alias: profile_form}

  app.form.profile:
    class: AppBundle\Form\ProfileType
    arguments: ['@security.authorization_checker']
    tags:
      - { name: form.type }

  app.event_listener.fosregistration_listener:
    class: AppBundle\EventListener\FOSRegistrationListener
    arguments: ['@doctrine.orm.entity_manager', '@fos_user.user_manager']
    tags:
      - { name: kernel.event_subscriber }
